opf/helm-charts

README.md

Depends on #5 without which updating the env variables would not result in a re-deployment of the openproject pod.

document how to update configuration

---

charts/openproject/Chart.yaml
charts/openproject/values.yaml

add commented example for setting the storageClass when using the bundled postgresql chart

---

.github/workflows/lint-test.yml
charts/openproject/Chart.yaml
charts/openproject/README.md
charts/openproject/templates/seeder-job.yaml
charts/openproject/templates/service.yaml
charts/openproject/templates/tests/test-connection.yaml
charts/openproject/templates/web-deployment.yaml
charts/openproject/templates/worker-deployment.yaml
charts/openproject/values.yaml

WP [#50645](https://community.openproject.org/projects/devops/work_packages/50645/activity)
This PR uses the `-slim` tag for the used images. To make that work the following things were done:
Depends on https://github.com/opf/openproject/pull/13826.

use slim image

---

charts/openproject/Chart.yaml
charts/openproject/templates/persistentvolumeclaim.yaml
charts/openproject/templates/seeder-job.yaml
charts/openproject/templates/web-deployment.yaml

This PR should be helpful in cases when the volume is managed outside this helm chart (for example, when the volume and PVC are created by Terraform In AWS.)

Add support for existing persistance claim

---

charts/openproject/Chart.yaml
charts/openproject/templates/seeder-job.yaml

Hey OpenProject Team :wave:,
the addition of annotations for the seeder Job were a brilliant idea, cause I need the annotation at the pod to apply NetworkPolicies.
...But the annotation were only available for the Job and not the created Pod - the PR should change this (already tested) :wink:

Use revision as suffix in job and add metadata

---

.changeset/bright-students-eat.md
charts/openproject/Chart.yaml
charts/openproject/README.md
charts/openproject/bin/debug
charts/openproject/bin/install-dev
charts/openproject/templates/_helpers.tpl
charts/openproject/templates/secrets.yaml
charts/openproject/templates/seeder-job.yaml
charts/openproject/templates/web-deployment.yaml
charts/openproject/templates/worker-deployment.yaml
charts/openproject/values.yaml

* currently trying to ways of creating tmp volumes for `/app/tmp` and `/tmp` respectively to allow for read-only root file systems
** `emptyDir`
** `epheremal` volume
At least on minikube both have problems with wrong permissions (world write access without sticky bit) which makes it unusable because Ruby will complain with the following.
```
irb(main):001:0> Dir.tmpdir
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
=> "/app"
```
Where `/app` is of course not writable and shouldn't be used to begin with.
I'm looking into the issue and will try to reproduce it on my OpenShift cluster.
If it's an issue specific to minikube we may not have a problem.
Edit: it works fine on mz OpenShift cluster. So it might really just be a minikube bug.
Will try this on another …

mount volumes for tmp directories, apply best practice to sc

---

.changeset/cuddly-pants-play.md
charts/openproject/templates/secret_s3.yaml

If you run the chart install with:
`helm upgrade --create-namespace --namespace openproject --install openproject openproject/openproject --dry-run -f values.yaml`
and you have defined s3 in your values.yaml:
```yaml
s3:
enabled: true
endpoint: "minio.local"
auth:
existingSecret: "minio-credentials"
secretKeys:
accessKeyId: "accessKeyId"
secretAccessKey: "secretAccessKey"
```
it fails with the following error: 
`Helm upgrade failed: YAML parse error on openproject/templates/secret_s3.yaml: error converting YAML to JSON: yaml: line 15: mapping values are not allowed in this context`
this is due to a whitespace formatting error in secret_s3.yaml which this pull request fixes.

Fix whitespace generation in s3 secret

---

.changeset/fix-s3-secret-lookup.md
charts/openproject/templates/secret_s3.yaml

Fix S3 secret lookup
There were two problems:
1. The namespace was hardcoded
2. The whitespace trimming was breaking the yaml
Now the lookup will be based on the namespace where the
release is being deployed, and the whitespace trimming
has been fixed.

Fix S3 secret lookup

---

.changeset/dry-snails-study.md
charts/openproject/README.md
charts/openproject/templates/secret_oidc.yaml
charts/openproject/values.yaml

Since we allow storing not only the secret access key but also the access key ID in the case of S3 I figured we should also do the same for OIDC so one can have both client ID and secret in the same place.
I have also amended the documentation to make it easier for beginners to create the respective secrets.

Feature: OIDC client id secret and docs

---

.changeset/great-ants-rest.md
.github/workflows/lint-test.yml
charts/openproject/README.md
charts/openproject/templates/_helpers.tpl
charts/openproject/values.yaml

The postgres chart will generate passwords automatically if needed, it turns out.

do not require a postgresql password anymore

---

.changeset/gentle-eyes-rest.md
charts/openproject/README.md
charts/openproject/templates/_helpers.tpl
charts/openproject/values.yaml
spec/charts/openproject/oidc_spec.rb
spec/helm_template.rb

Hello,
Please consider this as a enhancement suggestion as we are aware that this is not a bug from your side.
Please find our detailed reasoning for this below if needed as additional explanation.
This should allow usage in .Values.openproject.oidc.extraOidcSealedSecret pointing to custom generated sealed secret to load following values:
```
OPENPROJECT_OPENID__CONNECT_PROVIDERHERE_IDENTIFIER
OPENPROJECT_OPENID__CONNECT_PROVIDERHERE_SECRET
```  
As this separates IDENTIFIER and SECRET in sealed-secret, while rest of the OIDC configuration values are stored in Secret.
To have OpenProject Helm charts sealed-secrets loaded for OIDC working without using of `lookup` function ([ArgoCD related issue](https://github.com/argoproj/argo-cd/issues/5202))
Sealed-secret was created first:
```
``` …

Allows usage of sealed-secret for oidc `identifier` and `secret` values when helm template 'lookup' is not available

---

.changeset/strange-pillows-happen.md
charts/openproject/templates/secret_environment.yaml
charts/openproject/templates/secret_memcached.yaml
charts/openproject/templates/secret_oidc.yaml
charts/openproject/templates/secret_s3.yaml

stringData is always merged with the data of the existing secret
with this explicit reset values removed from, say, the environment value will not be removed, which is unexpected

make sure removed secret values are actually removed

---

.changeset/early-moons-fold.md
.changeset/manual-changeset-118.md
charts/openproject/templates/_helpers.tpl
charts/openproject/templates/seeder-job.yaml
charts/openproject/templates/web-deployment.yaml
charts/openproject/templates/worker-deployment.yaml
charts/openproject/values.yaml
spec/charts/openproject/extra_volumes_spec.rb
spec/helm_template.rb

This PR adds templates for additional volumes and their mounts in deployments/jobs. This is useful, when f.e. the truststore should be changed:
```yaml
extraVolumes:
- name: "trusted-cert-secret-volume"
secret:
secretName: "my-certificates-ca-tls"
items:
- key: "ca.crt"
path: "ca-certificates.crt"
extraVolumeMounts:
- name: "trusted-cert-secret-volume"
mountPath: "/etc/ssl/certs/ca-certificates.crt"
subPath: "ca-certificates.crt"
```

feat(openproject): Add extraVolumes and extraVolumeMounts option

---

.changeset/gorgeous-snakes-drum.md
charts/openproject/templates/_helpers.tpl
charts/openproject/values.yaml

charts/openproject/templates/_helpers.tpl: use .Values.persistence.storageClassName for /tmp and /app/tmp volumes, if it is defined

allow setting the storageClass for /tmp and /app/tmp volumes

---

.changeset/mighty-tigers-knock.md
charts/openproject/templates/seeder-job.yaml
charts/openproject/values.yaml
spec/charts/openproject/seeder_cleanup_spec.rb
spec/helm_template.rb

During our first steps in GitOps, we discovered that using a timestamp in job name, there is always display pending change (caused by the now ) - The revision should be a suitable replacement for this.
Additionally, there is now an option to control, weather a the seeder job is removed or not, again, needed for GitOps.

fix(openproject): Replace timestamp in job by revision

---

.changeset/sweet-laws-draw.md
charts/openproject/templates/secret_core.yaml
charts/openproject/values.yaml

Right now, you must have the ingress enabled in order to set the hostname of openproject. This change to the secret core allows the host to specified host value even when ingress is disabled. This is beneficial to users who are using the Gateway API HTTPRoutes instead of traditional Ingresses

Allow users to set the openproject host name without using the ingress

---

.changeset/beige-wombats-argue.md
charts/openproject/templates/service.yaml
charts/openproject/values.yaml

Hello :smile:
If service type is LoadBalanser, It can specify LoadBalanserIP.

Allow specified ipaddress for loadBalancerIP

---

.changeset/mighty-rocks-relax.md
charts/openproject/templates/web-deployment.yaml

Use the initdb.resources for wait-for-db too. This is necessary as we have LimitRange configured for a whole namespace. The init container fails with the default resource limit.

add resource limit for init-container

---

.changeset/chilly-eyes-bow.md
.changeset/great-clouds-fetch.md
charts/openproject/templates/seeder-job.yaml
charts/openproject/templates/web-deployment.yaml
charts/openproject/templates/worker-deployment.yaml
charts/openproject/values.yaml

Don't reuse initdb resources, but introduce our own

---

.changeset/old-tables-applaud.md
charts/openproject/Chart.yaml
charts/openproject/values.yaml

We have decided to start pinning the default OpenProject version so upgrading helm versions become easier. If a new version of OpenProject is released, we will bump the helm chart version.

Bump OpenProject to 14.6.0

---

.changeset/afraid-yaks-double.md
charts/openproject/templates/web-deployment.yaml
charts/openproject/values.yaml
spec/charts/openproject/web_strategy_spec.rb

If you use a RollingUpdate strategy, you can now set options like MaxSurge

Allow setting the web rollout strategy

---

.changeset/clean-apes-teach.md
charts/openproject/templates/secret_core.yaml
spec/charts/openproject/host_name_spec.rb

If there is no host or it's empty, we do not want to output it.

Allow unsetting the host name env OPENPROJECT_HOST__NAME 

---

.changeset/three-laws-sniff.md
charts/openproject/templates/seeder-job.yaml
charts/openproject/templates/web-deployment.yaml
charts/openproject/templates/worker-deployment.yaml

so used rails runner is guaranteed to work
specifically when appsignal is configured, it will try to write a log file and fail due to the read-only file system (if configured which it is by default)
This ought to fix the issue we are observing when appsignal is configured:
```
wait-for-db appsignal: Unable to log to '/app/log' or the '/tmp' fallback. Please check the permissions for the application's (log) directory.
```
It turns out, though, that this is not the main issue. The main issue is not appsignal at all but mini_magick since the latest update:
```
wait-for-db /usr/local/lib/ruby/3.4.0/tmpdir.rb:44:in 'Dir.tmpdir': could not find a temporary directory (ArgumentError)                                                                    
wait-for-db …
```

also provide writable tmp volumes for db init check

---

charts/openproject/templates/secret_core.yaml
charts/openproject/values.yaml

Allows to provide the admin user password with an existing secret as well as to define the key storing the password within the secret.

Add option to provide admin user password as an external secret

---

.changeset/clean-turtles-march.md
charts/openproject/templates/cron-deployment.yaml

Analogous to commit 846b5a7 provide writable tmp volumes to the init container `wait-for-db`.

fix: Provide writable tmp volumes for db init check in cronjob

---

.changeset/tricky-tables-reflect.md
charts/openproject/templates/worker-deployment.yaml
charts/openproject/values.yaml
spec/charts/openproject/worker_queues_spec.rb

Adding it will override the default of 20 by setting the env variable `OPENPROJECT_GOOD_JOB_MAX_THREADS`.
It needs to be an integer greater than 0.

Add maxThreads parameter to worker deployments

---

.changeset/tiny-hornets-hammer.md
charts/openproject/templates/cron-deployment.yaml
charts/openproject/templates/seeder-job.yaml
charts/openproject/templates/web-deployment.yaml
charts/openproject/templates/worker-deployment.yaml

Kubernetes `command` is for overriding the image entrypoint. `args` is what should be used instead. Otherwise all the fixes made in the image entrypoints (e.g. `PGBIN`) will be lost.
The seeder was correct.

Containers no longer override image entrypoint

---

.changeset/curly-tables-turn.md
README.md
charts/openproject/Chart.yaml
charts/openproject/values.yaml

Due to Bitnami's move to get rid of their free and public helm offering, we will need to find alternatives for the builtin packages (memacached, postgres). For testing purposes, we currently reference their legacy charts. Please note that they are not subject to updates nor security updates.
For production systems, we recommend you use their security offering, or alternatives (such as CNPG). We are interested in using these alternatives in our charts as well, feel free to provide pull requests to help us in that regard.
https://github.com/bitnami/charts/issues/35164

Switch to legacy repos until their public offering is clear
